sudo: required

services: 
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose build
  - docker-compose up -d
  - sudo docker-compose exec --user postgres appdb bash
  - psql
  - ALTER USER postgres WITH PASSWORD 'db_pass';
  - CREATE DATABASE nqueens;
  - \q
  - exit

script:
  - docker-compose exec web bash -c 'python -m pytest tests.py'
