sudo: required

services: 
  - docker

before_install:
  - docker version
  - docker-compose version

before_script:
  - docker-compose up -d

script:
  - docker-compose exec web bash -c 'python -m pytest tests.py'
