version: '3'

services:
  web:
    build: ./src
    volumes:
      - ./src:/code
    depends_on:
      - appdb
    tty: true

  appdb:
    image: postgres:10
    ports:
      - 15432:5432
    env_file:
      - ./config/postgres/database_env