version: '3'

services:
  web:
    build: ./src
    volumes:
      - ./src:/code
    networks:
      - database_network
    depends_on:
      - appdb
    tty: true

  appdb:
    image: postgres:10
    ports:
      - 15432:5432
    env_file:
      - ./config/postgres/database_env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

  
networks:
  database_network:
    driver: bridge

volumes:
  database_volume: